language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2.1.1

before_install:
  - sudo apt-get install tidy texlive-latex-base texlive-latex-recommended texlive-latex-extra

script: "bundle exec rake test"

matrix:
  allow_failures:
    - rvm: jruby-head
